Added docker compose file for local development
Dremet/csup_organizer pull request #1
Opened 2022-06-03 23:03 UTC by schuster-rainer

A docker compose file with all dependencies is create. Follow HACKME.md to startup the local database and server and start developing

2022-06-04 08:23 UTC, Dremet reviewed
Thanks for the input, left some comments :)

2022-06-04 08:23 UTC, Dremet commented on HACKME.md
> +python manage.py migrate
"makemigrations" is missing, isnt it?

2022-06-04 08:23 UTC, Dremet commented on HACKME.md
> +Navigate to http://localhost:8000/home
On the command line runserver will print 127.0.0.1, which obviously will show the same, but I'd prefer being consistent with the output. This is also relevant for the discord oauth configuration where the URL needs to match exactly

2022-06-04 08:23 UTC, Dremet commented on Pipfile
> +django = "*"
We should define the major version, e.g. Django 4

2022-06-04 08:23 UTC, Dremet commented on Pipfile
> +django = "*"
or does it use the requirements.txt file as well?

2022-06-04 08:23 UTC, Dremet commented on docker/init.sql
> +create database csup
where is the database name configured? Don't we need to make sure that this integrates with the settings.py file?

2022-06-04 08:23 UTC, Dremet commented on docker-compose.yaml
> +      POSTGRES_USER: ${DB_USER:-admin}
This I just don't know: Where does DB_USER come from and what does ":-admin" do?

2022-06-04 09:12 UTC, schuster-rainer commented on Pipfile
> +django = "*"
we can fix the version here to the major version. Subsequent install will install latest minior and bug fix release according to semver. At the point of installation the Pipfile.lock keeps the exact version of the point in time when the package was added. The requirements.txt is then created by pipenv running `pipenv lock -r > requirements.txt`. But it's only needed for deployment, if heroku or some other target doesn't understand the pipfile mechanics.

2022-06-04 09:12 UTC, schuster-rainer commented on HACKME.md
> +Navigate to http://localhost:8000/home
You 're probably talking about the redirect url. That's correct. Gonna change that

2022-06-04 09:14 UTC, schuster-rainer commented on HACKME.md
> +python manage.py migrate
The makemigrations is just creating the migrations from modelchanges, which should be already checked in. I think this should be another section, either describing the django workflow or just pointing to the official documentation. And btw. I'm going to change python manage.py to django-admin

2022-06-04 09:17 UTC, schuster-rainer commented on docker/init.sql
> +create database csup
I'm very pragmatic when it comes to things like this, but if django-admin provides some means to bootstrap the initial database creation I'm happy to do this. Another way to solve it is use a bash script for mounting to the init.d folder of postgress and just pass a ENV variable that is spliced in running the psql command line. But I'd prefer to use django-admin. I just need to get upto speed with it.

2022-06-04 09:19 UTC, schuster-rainer commented on docker-compose.yaml
> +      POSTGRES_USER: ${DB_USER:-admin}
the DB_USER coms from your environment. I'm going to provide a .env file example in this HACKEME.md. .env file is used by docker compose on startup.  ${DB_USER:-admin} means use the DB_USER env variable and if not given _fallback to the default_  '-' of `admin`

2022-06-04 19:06 UTC, Dremet requested changes

2022-06-04 19:06 UTC, Dremet commented on HACKME.md
> +python manage.py migrate
Doesnt it make more sense to create the migrations again from scratch instead of reusing all the migrations in the same order with back-and-fourth from the development phase?

2022-06-06 13:49 UTC, schuster-rainer commented on HACKME.md
> +python manage.py migrate
I probalby don't understand your request.... but migrations are migrations. If you feel the need to refactor the migrations for prod, go ahead. I never did this in rails. the makemigrations, as far is I assume will diff the model to the existing migrations and create the necessary migrations needed. My assumption as well is that migrations are created whenever a model is changed. When you forget to call makemigrations. Check in and i pull I'm going to miss the changes you did. So we could agree to just add this line to the docs for security reasons, but really the problem is that the migrations are not checked in in the first place.

As a remedey we could create a git commit hook that call makemigrations before every checking so that. the migrations actually reflect the necessary changes in a datamodel.

But I agree, we can just change it.

2022-06-07 11:23 UTC, Dremet approved these changes

2022-06-07 11:24 UTC, merged